### PR TITLE
Fraxlend Pairs + L2 ERC4626 Oracles & proofers

### PR DESCRIPTION
**Pull request by tom2o17**

### CODE REVIEW

**Comment by pegahcarter** [comment]
Can change base to master.

**Comment by tom2o17** [comment]
No timeline from me it would be a nice to have. 

But I do feel like the address scripts should be generate programmatically from the TS file, as well as the labels.

If this is something that got dropped happy to refactor this PR to add that functionality.

**Comment by pegahcarter** [comment]
@tom2o17 perhaps catch up with @FortisFortuna on the address / label generations?  I agree there should be some programmatic creation and synchrony between .ts and .sol.

**Comment by tom2o17** [comment]
Will open separate PR now that `generate:constants` script is working

**Pull request closed without merging**
